// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI-powered product recommendation flow.
 *
 * - `getProductRecommendations`: A function that recommends products based on items in the cart.
 * - `ProductRecommendationInput`: The input type for the `getProductRecommendations` function.
 * - `ProductRecommendationOutput`: The return type for the `getProductRecommendations` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ProductRecommendationInputSchema = z.object({
  cartItems: z
    .array(z.string())
    .describe('List of product IDs currently in the shopping cart.'),
  purchaseHistory: z
    .array(z.string())
    .optional()
    .describe('List of past product IDs purchased by the customer.'),
});
export type ProductRecommendationInput = z.infer<
  typeof ProductRecommendationInputSchema
>;

const ProductRecommendationOutputSchema = z.object({
  recommendedProductIds: z
    .array(z.string())
    .describe('List of product IDs recommended for the customer.'),
  reason: z
    .string()
    .describe('Explanation of why these products are recommended.'),
});
export type ProductRecommendationOutput = z.infer<
  typeof ProductRecommendationOutputSchema
>;

export async function getProductRecommendations(
  input: ProductRecommendationInput
): Promise<ProductRecommendationOutput> {
  return productRecommendationFlow(input);
}

const productRecommendationPrompt = ai.definePrompt({
  name: 'productRecommendationPrompt',
  input: {schema: ProductRecommendationInputSchema},
  output: {schema: ProductRecommendationOutputSchema},
  prompt: `You are an expert e-commerce product recommendation engine.

  Based on the items currently in the customer's cart and their past purchase history, recommend additional products that the customer may be interested in buying.

  Cart items: {{cartItems}}
  Purchase history: {{purchaseHistory}}

  Return a list of recommended product IDs and a brief explanation of why these products are recommended.
  Make sure to only recommend products that complement items already in cart.
  Do not recommend items already in cart.
  Ensure recommended products are relevant to Blue Drop water bottle packages and accessories.
  `,
});

const productRecommendationFlow = ai.defineFlow(
  {
    name: 'productRecommendationFlow',
    inputSchema: ProductRecommendationInputSchema,
    outputSchema: ProductRecommendationOutputSchema,
  },
  async input => {
    const {output} = await productRecommendationPrompt(input);
    return output!;
  }
);
